"""initial

Revision ID: 70a3882e97c9
Revises:
Create Date: 2026-05-28 05:00:01.124030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '70a3882e97c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())
    if 'audit_log' not in tables:
        op.create_table('audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('actor_user_id', sa.Integer(), nullable=True),
        sa.Column('actor_role', sa.String(length=32), nullable=True),
        sa.Column('action', sa.String(length=80), nullable=False),
        sa.Column('resource_type', sa.String(length=80), nullable=False),
        sa.Column('resource_id', sa.String(), nullable=True),
        sa.Column('patient_id', sa.Integer(), nullable=True),
        sa.Column('doctor_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        inspector = inspect(bind)

    existing_indexes = {idx['name'] for idx in inspector.get_indexes('audit_log')}
    if op.f('ix_audit_log_action') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    if op.f('ix_audit_log_actor_user_id') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    if op.f('ix_audit_log_created_at') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    if op.f('ix_audit_log_doctor_id') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_doctor_id'), 'audit_log', ['doctor_id'], unique=False)
    if op.f('ix_audit_log_id') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    if op.f('ix_audit_log_patient_id') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_patient_id'), 'audit_log', ['patient_id'], unique=False)
    if op.f('ix_audit_log_resource_id') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    if op.f('ix_audit_log_resource_type') not in existing_indexes:
        op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'audit_log' in set(inspector.get_table_names()):
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('audit_log')}
        for index_name in [
            op.f('ix_audit_log_resource_type'),
            op.f('ix_audit_log_resource_id'),
            op.f('ix_audit_log_patient_id'),
            op.f('ix_audit_log_id'),
            op.f('ix_audit_log_doctor_id'),
            op.f('ix_audit_log_created_at'),
            op.f('ix_audit_log_actor_user_id'),
            op.f('ix_audit_log_action'),
        ]:
            if index_name in existing_indexes:
                op.drop_index(index_name, table_name='audit_log')
        op.drop_table('audit_log')
    # ### end Alembic commands ###
